const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
  userId: {
    type: String,
    required: true,
    unique: true,
    index: true,
  },
  name: {
    type: String,
    required: true,
  },
  email: {
    type: String,
    required: true,
    unique: true,
    index: true,
  },
  
  // UPDATED: Added superadmin and supervisor roles
  role: {
    type: String,
    enum: ['superadmin', 'admin', 'coordinator', 'panel', 'supervisor', 'student'],
    required: true,
    index: true,
  },
  
  // NEW: First-Time Registration Authentication
  // Generated by Admin (e.g., "REG-9482") to verify identity on first device
  registrationCode: { 
    type: String,
    default: null
  },
  
  // ==========================================
  // ZKP AUTHENTICATION FIELDS
  // ==========================================
  
  zkpPublicKey: {
    type: String,
    default: null,
  },
  zkpRegistered: {
    type: Boolean,
    default: false,
    index: true,
  },
  zkpChallenge: {
    type: String,
    default: null,
  },
  zkpChallengeExpiry: {
    type: Date,
    default: null,
  },
  
  // Ephemeral fields for Secure Device Pairing (QR Sync & No-Camera Sync)
  zkpPairingCode: {
    type: String,  // A random 6-digit code or UUID
    default: null,
  },
  // NEW: Stores PC's temp key so phone can fetch it via 6-digit code without camera
  zkpTempPublicKey: {
    type: String,
    default: null,
  },
  zkpEncryptedPayload: {
    type: String,  // Temporarily holds the E2EE private key blob during transfer
    default: null,
  },
  zkpPairingExpiry: {
    type: Date,    // Expires very quickly (e.g., 2 minutes)
    default: null,
  },

  // Device/Session tracking
  authenticatedDevices: [{
    deviceId: {
      type: String,  // Unique device identifier
      required: true,
    },
    deviceName: {
      type: String,  // Browser + OS (e.g., "Chrome on Windows")
      required: true,
    },
    userAgent: {
      type: String,  // Full user agent string
    },
    ipAddress: {
      type: String,  // IP address
    },
    trustStatus: {
      type: Boolean,  // true = trusted, false = untrusted
      default: false,
    },
    lastLogin: {
      type: Date,
      default: Date.now,
    },
    registeredAt: {
      type: Date,
      default: Date.now,
    },
    isActive: {
      type: Boolean,
      default: true,
    }
  }],
  
  // Reset token for key reset by admin
  zkpResetToken: {
    type: String,
    default: null,
  },
  zkpResetTokenExpiry: {
    type: Date,
    default: null,
  },
  
  // ==========================================
  // STUDENT-SPECIFIC FIELDS
  // ==========================================
  
  matricNumber: {
    type: String,
    index: true,
  },
  program: {
    type: String,
  },
  researchTitle: {
    type: String,
  },
  supervisorId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  supervisorStatus: {
    type: String,
    enum: ['pending_panel_acceptance', 'pending_admin_approval', 'approved'],
    default: 'pending_panel_acceptance'
  },
  
  // ==========================================
  // PANEL-STUDENT ASSIGNMENT FIELDS
  // ==========================================
  
  assignedPanels: [{
    panelId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    startDate: {
      type: Date,
      required: true,
    },
    endDate: {
      type: Date,
      default: null,
    },
  }],
  
  assignedStudents: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  }],
  
  // ==========================================
  // SYSTEM FIELDS
  // ==========================================
  
  isActive: {
    type: Boolean,
    default: true,
    index: true,
  },
  lastLogin: {
    type: Date,
  },
}, {
  timestamps: true,
});

// ==========================================
// INDEXES
// ==========================================

userSchema.index({ userId: 1, zkpRegistered: 1 });
userSchema.index({ 'assignedPanels.panelId': 1 });
userSchema.index({ assignedStudents: 1 });
userSchema.index({ 'authenticatedDevices.deviceId': 1 });
userSchema.index({ supervisorId: 1 }); // Index for fast supervisor lookups

// ==========================================
// METHODS
// ==========================================

// Check if user has valid ZKP registration
userSchema.methods.hasValidZKP = function() {
  return this.zkpRegistered && !!this.zkpPublicKey;
};

// Check if challenge is still valid
userSchema.methods.hasValidChallenge = function() {
  if (!this.zkpChallenge || !this.zkpChallengeExpiry) {
    return false;
  }
  return new Date() <= this.zkpChallengeExpiry;
};

// Clear challenge data
userSchema.methods.clearChallenge = function() {
  this.zkpChallenge = null;
  this.zkpChallengeExpiry = null;
};

// Add authenticated device
userSchema.methods.addDevice = function(deviceInfo) {
  const existingDevice = this.authenticatedDevices.find(
    d => d.deviceId === deviceInfo.deviceId
  );
  
  if (existingDevice) {
    existingDevice.lastLogin = new Date();
    existingDevice.isActive = true;
    existingDevice.trustStatus = deviceInfo.trustStatus;
  } else {
    this.authenticatedDevices.push({
      deviceId: deviceInfo.deviceId,
      deviceName: deviceInfo.deviceName,
      userAgent: deviceInfo.userAgent,
      ipAddress: deviceInfo.ipAddress,
      trustStatus: deviceInfo.trustStatus,
      lastLogin: new Date(),
      registeredAt: new Date(),
      isActive: true,
    });
  }
};

// Remove device
userSchema.methods.removeDevice = function(deviceId) {
  this.authenticatedDevices = this.authenticatedDevices.filter(
    d => d.deviceId !== deviceId
  );
};

// Deactivate device (logout from device)
userSchema.methods.deactivateDevice = function(deviceId) {
  const device = this.authenticatedDevices.find(d => d.deviceId === deviceId);
  if (device) {
    device.isActive = false;
  }
};

// Logout all devices (force logout everywhere)
userSchema.methods.logoutAllDevices = function() {
  this.authenticatedDevices.forEach(device => {
    device.isActive = false;
  });
};

// Get active devices
userSchema.methods.getActiveDevices = function() {
  return this.authenticatedDevices.filter(d => d.isActive);
};

// FIXED: Moved this ABOVE module.exports so it actually registers to the schema!
userSchema.methods.clearPairingData = function() {
  this.zkpPairingCode = null;
  this.zkpPairingExpiry = null;
  this.zkpEncryptedPayload = null;
  this.zkpTempPublicKey = null; // Added new field
};

module.exports = mongoose.model('User', userSchema);